import { 
    create,
    NBadge,
    NButton,
    NCard,
    NDialog,
    NDialogProvider,
    NFlex,
    NGrid,
    NGridItem,
    NH2,
    NIcon,
    NLayout,
    NLayoutContent,
    NLayoutSider,
    NMessageProvider,
    NNumberAnimation,
    NPagination,
    NPopover,
    NScrollbar,
    NSpace,
    NText,
  } from 'naive-ui';
  
  
  export const naive = create({
    components: [
      NBadge,
      NButton,
      NCard,
      NDialog,
      NDialogProvider,
      NFlex,
      NGrid,
      NGridItem,
      NH2,
      NIcon,
      NLayout,
      NLayoutContent,
      NLayoutSider,
      NMessageProvider,
      NNumberAnimation,
      NPagination,
      NPopover,
      NScrollbar,
      NSpace,
      NText,
    ],
  });
  